### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by wootwoot1234** [rushout09/supportGPT#2]
I stumbled on this project when looking for a chatgpt solution for intercom. It looks perfect but wanted to check if you're actively using this in production and how your experience with it has been?

Thanks for building this, I'm excited to use it and help make it better!

**Comment by rushout09** [comment]
Hey sorry just say your issue here. We were using this in production but for my company hevo data, I had to create a separate repo and make it private :(

**Comment by wootwoot1234** [comment]
Thanks for writing. Will you be committing updates to this project or are you taking it offline?

**Comment by rushout09** [comment]
this project will stay but there will be no updates from my side here.
